### ISSUE TITLE
taskbar labels missing "shift+click" functionality to open new instance of process

### ISSUE THREAD

**Issue by twig-atl** [m417z/my-windhawk-mods#10]
on the normal taskbar, if you shift+click the toolbar icon it'll spawn a new instance

eg. clicking the taskbar label for an open instance of notepad will open a second instance of notepad

**Comment by m417z** [comment]
That sounds like an issue [Disable grouping on the taskbar](https://windhawk.net/mods/taskbar-grouping) sometimes causes. With this mod, Shift+click stops working for some items (folders, VSCode), but still works for others (Chrome, Calculator). Not sure why and I haven't looked at it yet, but a quick workaround I use is to right click and click on the app on the top of the menu instead.

**Comment by twig-atl** [comment]
huh interesting, you're right. Works with calculator but not notepad or vscode 🤔

**Comment by m417z** [comment]
Moved to https://github.com/ramensoftware/windhawk-mods/issues/158
