### ISSUE TITLE
display problem with mod "taskbar-labels"

### ISSUE THREAD

**Issue by SaiyajinK** [m417z/my-windhawk-mods#2]
Hello,

you can see for yourself the type of problem

while waiting for a fix.

see you

![C45j8XXchy](https://user-images.githubusercontent.com/105972098/190221973-6f72dc65-1505-4e2f-a88a-2c261747a529.png)

**Comment by Salsonn** [comment]
There's a lot of strange behavior I've seen surrounding switching between virtual desktops. Most labels will disappear after switching desktops until the window title is changed by the app, Apps will inherit the label of the calendar app if it was on the last active desktop?? This can be moved into a separate issue if it's different enough from everything else.

**Comment by Salsonn** [comment]
After updating to 22H2, the labels no longer get mixed inherit labels from other apps, they will just disappear until the title is changed.

**Comment by m417z** [comment]
Fixed in version 1.1 of the Taskbar Labels for Windows 11 mod. More details about the new version:
https://ramensoftware.com/windhawk-mod-update-taskbar-labels-for-windows-11

**Comment by SaiyajinK** [comment]
> Correction dans la version 1.1 des étiquettes de la barre des tâches pour le mod Windows 11. Plus de détails sur la nouvelle version : [https://ramensoftware.com/windhawk-mod-update-taskbar-labels-for-windows-11 ](https://ramensoftware.com/windhawk-mod-update-taskbar-labels-for-windows-11)

I'm on W11 professional 22H2 (build 22621.1265) and it's still misplaced unfortunately

![b7NPYIn7GQ](https://user-images.githubusercontent.com/105972098/224559016-aa9ac0bd-273b-415f-83c3-26bb71d8f8c8.png)

Is there a way to remove the play button ?

**Comment by m417z** [comment]
Why is it misplaced? Looks fine to me. How does it look without the mod?

> Is there a way to remove the play button ?

You can disable badges by turning off the "Show badges on taskbar apps" option [in taskbar properties](https://i.imgur.com/E4fyvks.png). Perhaps Media Player Classic has an option that controls it only for the player, I don't know.
