### ISSUE TITLE
system icon gap occurs when changing taskbar size below standard size when use "taskbar-icon-size"

### ISSUE THREAD

**Issue by SaiyajinK** [m417z/my-windhawk-mods#3]
Hello,
I installed the mod to resize the taskbar "taskbar-icon-size" and the system icons are shifted down when going below the standard size.

A solution ?
thank you

![VSCodium_ypMaXwtOuu](https://user-images.githubusercontent.com/105972098/190220648-732a7bf1-85ff-4dda-8ccf-c9b4c68204a7.png)

**Comment by Salsonn** [comment]
I'm able to replicate this on my machine. I'm using v1.0.1 of the mod, v0.9.2 of Windhawk, and build 22000.978 of Windows 11.

**Comment by m417z** [comment]
I suspect that it might not be an issue anymore on Windows 11 version 22H2. If you have the chance to update, please do and let me know whether you still see the issue.

**Comment by Salsonn** [comment]
Just updated to 22H2 and It still doesn't like to shrink that control down. Seems happy to make it bigger though!

**Comment by m417z** [comment]
It works correctly on an updated Windows 11 version 22H2. The bug you see happens on Windows 11 version 21H2, and maybe on 22H2 versions without updates. You can follow the issue here:
https://github.com/ramensoftware/windhawk-mods/issues/149
