### ISSUE TITLE
taskbar-labels - moving a window to the second display and back causes it to lose label

### ISSUE THREAD

**Issue by njdarda** [m417z/my-windhawk-mods#5]
Windhawk v0.9.2 beta (portable)
Taskbar Labels for Windows 11 - 1.0.2

This occurs when in Windows 11 `Personalisation > Taskbar > Taskbar behaviours > When using multiple displays, show my taskbar apps on` option is set to `Taskbar where window is open`

How to reproduce:
- open any window
- move it to the second monitor (the app will be moved correctly - with a label)
- move it back (the app will move but the label will become empty until updated)

**Comment by m417z** [comment]
Fixed in version 1.1 of the Taskbar Labels for Windows 11 mod. More details about the new version:
https://ramensoftware.com/windhawk-mod-update-taskbar-labels-for-windows-11
