### ISSUE TITLE
persistent order after restarts

### ISSUE THREAD

**Issue by gjs68** [m417z/my-windhawk-mods#6]
The taskbar-thumbnail-reorder is brilliant! This should be standard part of the OS itself. Timesaver!

Only after system restart (updates) or browser restart the tab labels remains but the re-arranged order is lost. Can the taskbar-thumbnail-reorder be made that the selected order is persistent through restarts?

**Comment by m417z** [comment]
Moved to https://github.com/ramensoftware/windhawk-mods/issues/155
