### ISSUE TITLE
Taskbar Labels for Windows 11 does not work upon restart, using dev channel build.

### ISSUE THREAD

**Issue by tobyisawesome** [m417z/my-windhawk-mods#7]
My Windows build is 25247.rs_prerelease.221114-1311 Dev Chanenel, I have restart my computer and Taskbar Labels continued to not run upon starting explorer.exe. 
![image](https://user-images.githubusercontent.com/71511385/204164221-561d76fa-f4f3-4007-9800-8f38140d3b84.png)
![image](https://user-images.githubusercontent.com/71511385/204164236-39dee8ee-fe45-4b74-9bcf-e72a302f8789.png)

**Comment by m417z** [comment]
Moved to https://github.com/ramensoftware/windhawk-mods/issues/156
